### ISSUE TITLE
ModelsDispatch incorrectly infers types.

### ISSUE THREAD

**Issue by minht11** [CaptainCodeman/rdx-model#8]
Reducers and effects paramaters Typescript types are infered incorrectly. For example payload boolean gets resolved to type never. 
`setVisibility(state: State, payload: boolean): State {}`
Tooltip: `(method) setVisibility(payload: never): void`
Test case can be seen here.
https://codesandbox.io/s/condescending-bardeen-g2l3w

**Comment by CaptainCodeman** [comment]
Thanks for the repro - I'll need to dig through this some more. I started working on some dtslint unit tests to make sure the typings work right so I'll try to factor these in.

Incidentally (when it's working correctly) it should infer the types for the reducer state so

```ts
setVisibility(state: State, payload: boolean): State {
  return { ...state, visible: payload }
}
```

can be shortened to:

```ts
setVisibility(state, payload: boolean) {
  return { ...state, visible: payload }
}
```

(The state type should come off the state property of the model)

**Comment by CaptainCodeman** [comment]
Released rc.2 which fixed this - thanks again for raising the issue and trying out the package!

**Comment by minht11** [comment]
Thx rc2 did fix preveous issue, but I noticed that optional paramaters are broken too. 
```ts
setVisibility(state, payload?: boolean)
setVisibility(state, payload = false)

dispatch.setVisibility(true) // Expected 0 arguments, but got 1.ts(2554).
```


Not really a big deal, but createModel does not enforce strict return type  so this works even though it shouldn't
```ts
setVisibility(state, payload: boolean) {
  return { ...state, thisPropertyDoesNotExistInState: payload }
}
```
Adding explicit return type on function fixes this. The same thing happens with Rematch library so I am not sure if it's actually fixable, but it would be a nice thing to have.
